---
title: "GDD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GDD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#library(stotzgdh) #does not load
pacman::p_load("DT", "tidyverse")
```


```{r gdh}
gdh <- function(..., crop, crop_data) {
  crop_subset <- subset(crop_data, crop_name == crop)
  # Obtain base temp value from crop_data based on crop
  base_temp <- as.numeric(crop_subset[1,2])
  # Obtain upper threshold value from crop_data based on crop
  threshold <- as.numeric(crop_subset[1,4])
  # Check for NA values using is.na() and return NA if any temperature values are missing
  if (any(is.na(c(...)))) {
    return(NA)
  } else {
    # Replace negative values with zero using pmax()
    # Replace values exceeding the threshold with the threshold value
    values <- pmax(pmin(..., threshold)-base_temp, 0)
    # Take the sum of the values, hence summing 24 GDH values into a GDD value
    return(sum(values))
  }
}
```

## Prior Knowledge Needed

* Understanding of threshold temperatures for crops (high and low)
* Basic Algebra

# 
